---
- name: "Publish lifecyle environments for content view {{ item.content_view }}"
  theforeman.foreman.content_view_version:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    content_view: "{{ item.content_view }}"
    organization: "{{ foreman_organization }}"
    version: "{{ item.content_view_update | d(false) | ternary(omit, 1.0) }}"
    #lifecycle_environments: "{{ item.lifecycle_environments | first }}"
    lifecycle_environments: "{{ item.lifecycle_environments }}"
  async: "{{ publish_timeout }}"
  poll: 0
  register: publish_async

- name: Check if lifecyle environments publish job is complete for content view {{ item.content_view }}
  async_status:
    jid: "{{ publish_async.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: "{{ ( publish_timeout / publish_retry_interval ) | int }}"
  delay: "{{ publish_retry_interval }}"
